# Generated by Django 6.0.6 on 2026-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(default='Autofya Meeting — 30 Minute Meeting', max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('guest_emails', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('situation', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_range', models.CharField(blank=True, max_length=100, null=True)),
                ('engagement_type', models.CharField(blank=True, max_length=100, null=True)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('hear_about_us', models.CharField(blank=True, max_length=100, null=True)),
                ('must_work_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
