# Generated by Django 6.0.5 on 2026-05-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['is_superuser', '-is_staff', '-created_at']},
        ),
    ]
