# Generated by Django 6.0.6 on 2026-09-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_full_name_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_lock_price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_start_date',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
