# Generated by Django 6.0.6 on 2026-09-16 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.CharField(db_index=True, max_length=100)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(default='desktop', max_length=50)),
                ('page_url', models.CharField(db_index=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
